// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJl9ACIrl5gBAb3yNPs7b_5VelfeiSGYg',
    appId: '1:617045879095:web:0990a194c9aaadfba6d2b2',
    messagingSenderId: '617045879095',
    projectId: 'fir-96a0a',
    authDomain: 'fir-96a0a.firebaseapp.com',
    storageBucket: 'fir-96a0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVlhyTzEYVeBnw0gkRIeKXIa5scADs7c',
    appId: '1:617045879095:android:157ca8d9a8b8b5dea6d2b2',
    messagingSenderId: '617045879095',
    projectId: 'fir-96a0a',
    storageBucket: 'fir-96a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBDUNahXN_Kw6ZF7HFgi3Pn2sZLV7iO8M',
    appId: '1:617045879095:ios:71afada6ef6af32ea6d2b2',
    messagingSenderId: '617045879095',
    projectId: 'fir-96a0a',
    storageBucket: 'fir-96a0a.appspot.com',
    iosBundleId: 'com.example.audi',
  );
}
